inherit_gem:
  rubocop-gp:
    - ./config/default.yml

Gp/OptArgParameters:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - lib/active_dry_form/builder.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Rails/Delegate:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
